version: 2.0
jobs:
build:
docker:
  - image: circleci/node:8.11.4
filters:

## 分支过滤，很重要，不然gh-pages 会报错，

  branches:
    only:
    - master
steps:
  - checkout
  - run:
      name: Deploying to GitHub Pages
      command: |
        git config --global user.email "1292028314@qq.com"  ## git 的一些配置
        git config --global user.name "huangxinglong"
        echo "machine github.com login huangxinglong password $GITHUB_TOKEN" > ~/.netrc  ## 基于github token 的登录
        cd website && yarn install && GIT_USER=rongfengliang yarn run publish-gh-pages ## npm script 执行
